#!/bin/sh

cargo check --profile ci --workspace --all-targets
cargo clippy --profile ci --workspace --all-targets -- -D warnings
cargo test --profile ci --workspace --all-targets
cargo build --profile ci --workspace --all-targets
cargo package
